queue=[]
queue.append('m')
queue.append('n')
queue.append('o')
print("initial queue")
print(queue)
print("\nelements dequeued from queue")
print(queue.pop(0))
print(queue.pop(0))
print(queue.pop(0))
print("\nqueue after removing elements")
print(queue)
